export const slides = [
  {
    type: "glb",
    path: "socarlogo.glb",
    duration: 18,
    year: "Intro",
    text: "The History of SOCAR",
    transform: { position: [0, 1, 0], scale: [0.5, 0.5, 0.5], rotation: [0, 0, 0] },
    animation: "scale_up",
  },
  {
    type: "spz",
    path: "citypano.spz",
    duration: 18,
    year: "Medieval",
    text: "Azerbaijan’s oil was repeatedly described in the works of medieval scholars and travelers as a great source of income.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    }, 
  },
  {
    type: "spz",
    path: "marcopolo.spz",
    duration: 18,
    year: "14th C.",
    text: "As Marco Polo wrote in the 14th century, people in this region used oil for medicinal purposes as well as for export.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "refinery.spz",
    duration: 18,
    year: "1594",
    text: "Inscriptions on a stone found in a well in Balakhany, say it was drilled by foreman Allahyar Mammad Nuroghlu in 1594.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "oilwell.spz",
    duration: 18,
    year: "1847",
    text: "1847. A turning point in oil production was reached in the 19th century, and in 1847 the first oil wells were mechanically drilled at Bibiheybat and at Balakhany.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "pipeline.spz",
    duration: 18,
    year: "1859",
    text: "1859. The first white oil refinery (facility) was built in Baku. 1876. A deep well pump was applied for the first time, preceding the USA by 15 years.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "hotel.spz",
    duration: 18,
    year: "1877",
    text: "1877. The Nobel brothers founded an oil production and processing company in Baku. Assets included oil fields, refineries, the world's first oil tanker in the Caspian Sea, barges, railways, hotels and more.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "train.spz",
    duration: 18,
    year: "1878",
    text: "1878. The railway connecting the oil fields with the refineries financed by the 'Nobel Brothers' company completed in April 1879.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "rigs.spz",
    duration: 18,
    year: "1907",
    text: "1907. Baku's oil industry ranked first in the world with a production of 11.5 million tons per year. The world's longest main oil pipeline, Baku-Batumi, was built at that time.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "glb",
    path: "socar1992.glb",
    duration: 18,
    year: "1930",
    text: "1930. For the first time, electric logging and measurement of the degree of inclination in the borehole was implemented in Baku.",
    transform: {
      position: [0, 0.5, 0],
      scale: [0.25, 0.25, 0.25],
      rotation: [0, 0, 0],
    },
  },
  {
    type: "spz",
    path: "state.spz",
    duration: 18,
    year: "1941",
    text: "1941. 71.4% of total Soviet oil was produced by Azerbaijan (23.5 million tons). This production guaranteed the victory of the Soviet Union in World War II.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "platforms.spz",
    duration: 18,
    year: "1949",
    text: "1949. Azerbaijan was also the first offshore oil producer in the world. On November 7, 1949, the Neft Dashlari ('Oil Rocks') field was discovered.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "img",
    path: "map1.png",
    duration: 18,
    year: "1970-80",
    text: "1970 to 1980. The Azeri, Chirag, Kapaz and Gunashli fields were discovered in water 80 to 350 meters deep. Gunashli currently produces more than 60% of SOCAR's oil.",
    transform: {
      position: [0, 1.5, -1],
      scale: [2, 1.125, 1],
      rotation: [0, 0, 0],
    },
  },
  {
    type: "img",
    path: "map2.png",
    duration: 18,
    year: "1992",
    text: "The billionth ton of oil was produced in Azerbaijan. 1992. By the Decree of the President, the Oil Company of state of the Republic of Azerbaijan.",
    transform: {
      position: [0, 1.5, -1],
      scale: [2, 1.125, 1],
      rotation: [0, 0, 0],
    },
  },
  {
    type: "spz",
    path: "flag.spz",
    duration: 18,
    year: "1994",
    text: "1994. On September 20, the Joint Development and Production Sharing Agreement for the Azeri, Chirag and Gunashli fields was signed. This became known as the 'Contract of the Century'.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "contract.spz",
    duration: 18,
    year: "Signed",
    text: "The agreement, signed by 11 oil companies from 8 countries was a sign of wisdom and political courage. Increased confidence encouraged oil companies to come here.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "img",
    path: "map3.png",
    duration: 18,
    year: "1996",
    text: "1996. Joint development agreement for the Shahdeniz condensate field. 1997. Baku-Novorossiysk pipeline. 1999. Baku-Supsa pipeline.",
    transform: {
      position: [0, 1.5, -1],
      scale: [2, 1.125, 1],
      rotation: [0, 0, 0],
    },
  },
  {
    type: "spz",
    path: "modern.spz",
    duration: 18,
    year: "2001",
    text: "2001. Oilman's Day. 2006. BTC pipeline inauguration. 2007. South Caucasus Pipeline and first gas export.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "station.spz",
    duration: 18,
    year: "2008",
    text: "2008. SOCAR Trading S.A. established in Geneva. SOCAR acquired PETKIM in Turkey and accelerated operations.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "2billion.spz", 
    duration: 18,
    year: "2009",
    text: "2009-2011. Fuel distribution in Ukraine, Georgia, Romania, Switzerland. 2017. Azerbaijan produced two billion tons of oil.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "stage.spz",
    duration: 18,
    year: "2018",
    text: "2018. STAR refinery inaugurated. TANAP opened. SOCAR Turkey won tender for Istanbul Airport gas stations.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "spz",
    path: "pipes.spz",
    duration: 18,
    year: "2020",
    text: "2020. The Trans-Adriatic Gas Pipeline (TAP) began transporting commercial gas from Azerbaijan.",
    transform: {
      position: [0, 1, -2],
      scale: [3.0, 3.0, 3.0],
      rotation: [0, 3.14, 3.14],
    },
  },
  {
    type: "glb",
    path: "socarlogo.glb",
    duration: 18,
    year: "End",
    text: "Thank you for watching.",
    transform: { position: [0, 1, 0], scale: [0.5, 0.5, 0.5], rotation: [0, 0, 0] },
  },
];
